
export const CHANGE_AUTH = 'CHANGE_AUTH';
export const CHANGE_ROLLNUMBER = 'CHANGE_ROLLNUMBER';
export const CHATS_FETCHED = 'CHATS_FETCHED';
export const CHANGE_USERNAME = 'CHANGE_USERNAME';
export const CHANGE_AUTH_BOOL = 'CHANGE_AUTH_BOOL';
export const TOGGLE_BULB = 'TOGGLE_BULB';
export const USER_REGISTERED = 'USER_REGISTERED';
export const USER_LOGOUT = 'USER_LOGOUT';

export const ADD_APPOINTMENTS = 'ADD_APPOINTMENTS';

